# ─────────────────────────────────────────────
#  CONFIG — change these to switch domains
# ─────────────────────────────────────────────

# Domain label (used in prompts and reports)
CURRENT_DOMAIN = "finance"

# Path to your RAG JSONL file (generated by generate_rag_contexts_mac.py)
RAG_FILE = "rag_llm_stress/finance_contexts.jsonl"

# Model used to GENERATE questions (must be available in Ollama)
GENERATOR_MODEL = "mistral:latest"

# Model being TESTED for hallucinations
TEST_MODEL = "llama3.1:latest"

# How many stress-test rounds to run
# 200 minimum for reliable per-category percentages
# 500+ for publication-grade conclusions
NUM_STEPS = 200

# How many RAG documents to retrieve per question
RAG_TOP_K = 2

# Question categories
CATEGORIES = [
    "factual",       # single correct answer grounded in context
    "misleading",    # contains a false assumption
    "reasoning",     # requires multi-step thinking
    "ambiguous",     # no single correct answer
]

DOMAINS = [CURRENT_DOMAIN]

# Output report file
REPORT_FILE = "results.jsonl"